apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  containers:
    - name: postgres
      image: postgres:12
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      env:
        - name: POSTGRES_PASSWORD
          value: postgrespassword
      ports:
        - containerPort: 5432
  volumes:
    - name: db-data
      emptyDir: {}
