apiVersion: v1
kind: Service
metadata:
  name: hasura
  labels:
    app: hasura
spec:
  ports:
    - port: 8092
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: hasura
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-deployment
  labels:
    app: hasura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hasura
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hasura
      annotations:
        scriptExecutedAt: 'dummyvalue'
    spec:
      serviceAccountName: hasura-deployment-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'hasura-deployment-secret'
      containers:
        - name: hasura
          image: hasura/graphql-engine:v2.18.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8092
          volumeMounts:
            - name: secrets-store-inline
              mountPath: '/mnt/secrets-store'
              readOnly: true
          env:
            - name: HASURA_GRAPHQL_CONSOLE_ASSETS_DIR
              value: /srv/console-assets
            - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
              value: postgres://postgres:postgrespassword@postgres:5432/postgres
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://postgres:postgrespassword@postgres:5432/postgres
            ## enable the console served by server
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: 'true'
            ## enable debugging mode. It is recommended to disable this in production
            - name: HASURA_GRAPHQL_DEV_MODE
              value: 'true'
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: rotatingsecrethasura
