apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-pod-deployment
  labels:
    app: secret-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-pod
  template:
    metadata:
      labels:
        app: secret-pod
    spec:
      serviceAccountName: hasura-deployment-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: hasura-deployment-secret
      containers:
        - name: secret-refresh-pod
          image: jgomatos/secret-refresh-pod-aws:v1.0.4
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets-store-inline
              mountPath: '/usr/app/secrets-store'
              readOnly: true
